function   imxshow_lep_v2(X,varargin)
%  
% Enping Lin  20240703


% filename = '/ContainerFolder1/radial/code/common/imxshow.m';
% if exist(filename, 'file') == 2
%     addpath( ('/ContainerFolder1/radial/code/common/')  );
% else
%     error(['imxshow.m does not exist in %s',filename]);
% end
 

[figName,yxz,flipind,layout,plane] = process_options_lep(varargin,'Name','This is a figure generated by imxshow_lep_v2','yxz',[],'flip',[],'layout',[],'plane','axial' );




if iscell(X)

   for it = 1:length(X)
        switch plane
            case {'axial','Axial','A','a','AXIAL','tranverse','Tranverse','T','TRANVERSE','t'}
             
            case {'saggital','Saggital','S','SAGGITAL','s'}    
              X{it} = permute(X{it},[3,1,2,4]);
              X{it} = flip(X{it},1);
            case {'coronal','Coronal','C','CORONAL','c'}
              X{it} = permute(X{it},[3,2,1,4]);
              X{it} = flip(X{it},1);
        end      

       if length(yxz)>0
          X{it} = permute(X{it},[yxz,4]);
       end
       if length(flipind)>0
          X{it} = flip(X{it},flipind);
       end

       X{it} = NormalizedImage_lep(X{it});
   end

   if  ~isempty(layout)
       X = X(:);
       if length(X)<prod(layout)
          warning('Image number is less than Layout and zeros images are filled')
       elseif length(X)>prod(layout) 
          warning('Image number is greater than Layout and only the top %d images are displayed',prod(layout)) 
       end    
       X = reshape(X,layout);
   end    
   X = reshape(X,size(X,1),size(X,2),1,1);
   X = cell2mat(X);

elseif isnumeric(X)
    switch plane
        case {'axial','Axial','A','AXIAL','tranverse','Tranverse','T','TRANVERSE','t','a'}
         
        case {'saggital','Saggital','S','SAGGITAL','s'}    
          X  = permute(X,[3,1,2,4]);
          X = flip(X,1);
        case {'coronal','Coronal','C','CORONAL','c'}
          X = permute(X,[3,2,1,4]);
          X = flip(X,1);
    end
    if length(yxz)>0
      X = permute(X,[yxz,4]);
    end
    if length(flipind)>0
       X = flip(X,flipind);
    end

end  

  imxshow(X),set(gcf,"Name",figName)
   
end